minimumReleaseAge: 10080
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - next
  - bcrypt
  - protobufjs

ignoreDepScripts: true
childConcurrency: 10
engineStrict: true
autoInstallPeers: false
peerDependencyRules:
  allowedVersions:
    react: "19"
    "react-dom": "19"
