# minimumReleaseAge: 10080
onlyBuiltDependencies:
  - next
  - prisma
  - "@prisma/client"
  - bcrypt
  - protobufjs
  - tailwindcss

overrides:
  "@auth/core": "$@auth/core"

ignoreDepScripts: true
childConcurrency: 10
engineStrict: true
autoInstallPeers: false
dedupePeerDependents: true
peerDependencyRules:
  allowedVersions:
    react: "19"
    "react-dom": "19"
