# minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - webpack@4.47.0 || 5.102.1
onlyBuiltDependencies:
  - next
  - prisma
  - "@prisma/client"
  - bcrypt
  - protobufjs

ignoreDepScripts: true
childConcurrency: 10
engineStrict: true
autoInstallPeers: false
peerDependencyRules:
  allowedVersions:
    react: "19"
    "react-dom": "19"
